Nhom14_ChuDu/Models/KhuyenMai.cs
namespace Nhom14_ChuDu.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("KhuyenMai")]
    public partial class KhuyenMai
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KhuyenMai()
        {
            ChiTietKhuyenMais = new HashSet<ChiTietKhuyenMai>();
        }

        [Key]
        [Required(ErrorMessage = "ID khuyến mãi không được để trống !")]
        [DisplayName("ID Khuyến mãi")]
        public int IDKhuyenMai { get; set; }

        [Required(ErrorMessage = "Tên khuyến mãi không được để trống !")]
        [DisplayName("Tên")]
        public string Ten { get; set; }

        [Required(ErrorMessage = "Mô tả khuyến mãi không được để trống !")]
        [DisplayName("Mô tả")]
        public string MoTa { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietKhuyenMai> ChiTietKhuyenMais { get; set; }
    }
}

Nhom14_ChuDu/Controllers/KhuyenMaisController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Nhom14_ChuDu.Models;
using PagedList;

namespace Nhom14_ChuDu.Controllers
{
    public class KhuyenMaisController : Controller
    {
        private ChuDu24 db = new ChuDu24();

        // GET: KhuyenMais
        public ActionResult Index(string sortOrder, string searchString, string currentFilter, int? page)
        {
            //các biến sắp xếp
            ViewBag.CurrentSort = sortOrder;

            ViewBag.SapTheoTen = String.IsNullOrEmpty(sortOrder) ? "ten_desc" : "";

            //lấy giá trị của bộ lọc dữ liệu hiện tại
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter = searchString;

            var khuyenMais = db.KhuyenMais.Select(km => km);

            //lọc theo tên hàng
            if (!String.IsNullOrEmpty(searchString))
            {
                khuyenMais = khuyenMais.Where(km => km.Ten.Contains(searchString));
            }
            switch (sortOrder)
            {
                case "ten_desc":
                    khuyenMais = khuyenMais.OrderByDescending(km => km.Ten);
                    break;
                default:
                    khuyenMais = khuyenMais.OrderBy(km => km.Ten);
                    break;
            }


            //khuyenMais = khuyenMais.OrderBy(km => km.IDKhuyenMai);
            int pageSize = 5;
            int pageNumber = (page ?? 1);

            return View(khuyenMais.ToPagedList(pageNumber, pageSize));
        }

        // GET: KhuyenMais/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            KhuyenMai khuyenMai = db.KhuyenMais.Find(id);
            if (khuyenMai == null)
            {
                return HttpNotFound();
            }
            return View(khuyenMai);
        }

        // GET: KhuyenMais/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: KhuyenMais/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IDKhuyenMai,Ten,MoTa")] KhuyenMai khuyenMai)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.KhuyenMais.Add(khuyenMai);
                    db.SaveChanges();
                }
                    return RedirectToAction("Index");
            }
            catch(Exception ex)
            {
                ViewBag.Error = "Lỗi nhập dữ liệu !" + ex.Message;
                return View(khuyenMai);
            }
        }

        // GET: KhuyenMais/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            KhuyenMai khuyenMai = db.KhuyenMais.Find(id);
            if (khuyenMai == null)
            {
                return HttpNotFound();
            }
            return View(khuyenMai);
        }

        // POST: KhuyenMais/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IDKhuyenMai,Ten,MoTa")] KhuyenMai khuyenMai)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Entry(khuyenMai).State = EntityState.Modified;
                    db.SaveChanges();
                }
                    return RedirectToAction("Index");
            }
            catch(Exception ex)
            {
                ViewBag.Error = "Lỗi nhập dữ liệu !" + ex.Message;
                return View(khuyenMai);
            }
        }

        // GET: KhuyenMais/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            KhuyenMai khuyenMai = db.KhuyenMais.Find(id);
            if (khuyenMai == null)
            {
                return HttpNotFound();
            }
            return View(khuyenMai);
        }

        // POST: KhuyenMais/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            KhuyenMai khuyenMai = db.KhuyenMais.Find(id);
            try
            {
                db.KhuyenMais.Remove(khuyenMai);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ViewBag.Error = "Không được xóa bản ghi này !" + ex.Message;
                return View("Delete", khuyenMai);
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Nhom14_ChuDu/Views/KhuyenMais/Create.cshtml
@model Nhom14_ChuDu.Models.KhuyenMai

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Admin.cshtml";
}


<h2>Tạo mới</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>KhuyenMai</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Ten, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ten, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ten, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MoTa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MoTa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MoTa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Tạo" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Trở lại danh sách khuyến mãi", "Index")
</div>

@if (ViewBag.Error != null)
{
    <br />
    <div class="alert alert-danger" role="alert">@ViewBag.Error</div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Nhom14_ChuDu/Views/KhuyenMais/Delete.cshtml
@model Nhom14_ChuDu.Models.KhuyenMai

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Admin.cshtml";
}

<h2>Xóa</h2>

<h3>Bạn chắc chắn muốn xóa?</h3>
<div>
    <h4>KhuyenMai</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Ten)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ten)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MoTa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MoTa)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Xóa" class="btn btn-default" /> |
            @Html.ActionLink("Trở lại danh sách khuyến mãi", "Index")
        </div>
    }
</div>

@if (ViewBag.Error != null)
{
    <br />
    <div class="alert alert-danger" role="alert">@ViewBag.Error</div>
}

Nhom14_ChuDu/Views/KhuyenMais/Details.cshtml
@model Nhom14_ChuDu.Models.KhuyenMai

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Admin.cshtml";
}

<h2>Chi tiết</h2>

<div>
    <h4>KhuyenMai</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Ten)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ten)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MoTa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MoTa)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Sửa", "Edit", new { id = Model.IDKhuyenMai }) |
    @Html.ActionLink("Trở lại danh sách khuyến mãi", "Index")
</p>

Nhom14_ChuDu/Views/KhuyenMais/Edit.cshtml
@model Nhom14_ChuDu.Models.KhuyenMai

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Admin.cshtml";
}

<h2>Sửa</h2>


@using (Html.BeginForm(Html.BeginForm("Edit", "KhuyenMais", FormMethod.Post, new { enctype = "multipart/form-data" })))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>KhuyenMai</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IDKhuyenMai)

        <div class="form-group">
            @Html.LabelFor(model => model.Ten, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ten, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ten, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MoTa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MoTa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MoTa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lưu" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Trở lại danh sách khuyến mãi", "Index")
</div>

@if (ViewBag.Error != null)
{
    <br />
    <div class="alert alert-danger" role="alert">@ViewBag.Error</div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Nhom14_ChuDu/Views/KhuyenMais/Index.cshtml
@model PagedList.IPagedList<Nhom14_ChuDu.Models.KhuyenMai>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Admin.cshtml";
}

<h2 style="margin-top:50px;">Khuyến mãi</h2>

<p>
    @Html.ActionLink("Tạo mới", "Create")
</p>

@using (Html.BeginForm())
{
    <p>
        Tìm khuyến mãi: @Html.TextBox("searchString", ViewBag.CurrentFilter as string)
        <input type="submit" value="Tìm" />
    </p>
}

<table class="table">
    <tr>
        <th>
            @Html.ActionLink("Tên khuyến mãi", "Index", new
               {
                   sortOrder = ViewBag.SapTheoTen,
                   currentFilter = ViewBag.CurrentFilter
               })
        </th>
        <th>
            Mô tả
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Ten)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MoTa)
            </td>
            <td  style="text-align:center;">
                @Html.ActionLink("Sửa", "Edit", new { id = item.IDKhuyenMai }) |
                @Html.ActionLink("Chi tiết", "Details", new { id = item.IDKhuyenMai }) |
                @Html.ActionLink("Xóa", "Delete", new { id = item.IDKhuyenMai })
            </td>
        </tr>
    }

</table>

Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount
@Html.PagedListPager(Model, page => Url.Action("Index", new { page }))