Nhom14_ChuDu/Controllers/KhachSansController.cs
using System;
using System.Collections.Generic;
using System.Collections;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Nhom14_ChuDu.Models;
using PagedList;
using System.IO;

namespace Nhom14_ChuDu.Controllers
{
    public class KhachSansController : Controller
    {
        private ChuDu24 db = new ChuDu24();

        // GET: KhachSans
        public ActionResult Index__Admin(string sortOrder, string searchString, string currentFilter, int? page)
        {
            //các biến sắp xếp
            ViewBag.CurrentSort = sortOrder;

            ViewBag.SapTheoTen = String.IsNullOrEmpty(sortOrder) ? "ten_desc" : "";

            //lấy giá trị của bộ lọc dữ liệu hiện tại
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter = searchString;

            var khachSans = db.KhachSans.Include(k => k.ThanhPho);

            //lọc theo tên hàng
            if (!String.IsNullOrEmpty(searchString))
            {
                khachSans = khachSans.Where(k => k.Ten.Contains(searchString));
            }
            switch (sortOrder)
            {
                case "ten_desc":
                    khachSans = khachSans.OrderByDescending(k => k.Ten);
                    break;
                default:
                    khachSans = khachSans.OrderBy(k => k.Ten);
                    break;
            }

            //khachSans = khachSans.OrderBy(k => k.IDKS);
            int pageSize = 5;
            int pageNumber = (page ?? 1);

            return View(khachSans.ToPagedList(pageNumber, pageSize));
        }


        public ActionResult Index__detail(string sortOrder, string searchString, string currentFilter, int? page)
        {
            var topphongdat = db.PhongKS.OrderByDescending(u => u.DatPhongs.Count).Take(3);

            return View(topphongdat.ToList());
        }

        public ActionResult Index(string sortOrder, string searchString, string curentFilter, int? page)
        {
            ViewBag.SapTheoTen = String.IsNullOrEmpty(sortOrder) ? "ten_desc" : "";

            //Lấy gtri cảu bộ lọc hiện tại;
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = curentFilter;
            }
            ViewBag.curentFilter = searchString;

            var khachsan = db.KhachSans.Select(p => p);

            //Lọc theo tên hàng
            if (!String.IsNullOrEmpty(searchString))
            {
                khachsan = khachsan.Where(p => p.Ten.Contains(searchString));
            }


            switch (sortOrder)
            {
                case "ten_desc":
                    khachsan = khachsan.OrderByDescending(s => s.Ten);
                    break;
                default:
                    khachsan = khachsan.OrderBy(s => s.Ten);
                    break;
            }
            int pageSize = 3;
            //Nếu trang null trả về 1
            int pageNumber = (page ?? 1);

            return View(khachsan.ToPagedList(pageNumber, pageSize));

        }
        public PartialViewResult _DsKhachSan()
        {
            var khachSans = db.KhachSans.Select(p => p);
            return PartialView(khachSans);
        }
        public PartialViewResult TimKhachSan()
        {
            
            if(Request["city"] != "df" && Request["hotel"] == "")
            {
                int ID = int.Parse(Request["city"]);
                var khachSans = db.KhachSans.Where(p => p.IDThanhPho == ID);
                return PartialView(khachSans);
            }
            else if(Request["hotel"] != "" && Request["city"] == "df")
            {
                string tenKS = Request["hotel"];
                var khachSans = db.KhachSans.Where(p => p.Ten.ToLower().Contains(tenKS.ToLower()));
                return PartialView(khachSans);
            }
            else if (Request["city"] != "df" && Request["hotel"] != "")
            {
                int ID = int.Parse(Request["city"]);
                string tenKS = Request["hotel"];
                var tp = db.KhachSans.Where(p => p.IDThanhPho == ID);
                var khachSans = tp.Where(p => p.Ten == tenKS);
                return PartialView(khachSans);
                
            }
            return PartialView();
            
        }

        public ActionResult Detail(string id)
        {
            int maKS = int.Parse(id);
            var phongKS = db.PhongKS.Where(p => p.IDKS.Equals(maKS) && p.ChiTietKhuyenMais.Count() > 0);
            return View(phongKS.ToList());
        }

        // GET: KhachSans/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            KhachSan khachSan = db.KhachSans.Find(id);
            if (khachSan == null)
            {
                return HttpNotFound();
            }
            return View(khachSan);
        }

        // GET: KhachSans/Create
        public ActionResult Create()
        {
            ViewBag.IDThanhPho = new SelectList(db.ThanhPhoes, "IDThanhPho", "Ten");
            return View();
        }

        // POST: KhachSans/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IDKS,Ten,DiaChi,Anh,MoTa,IDThanhPho")] KhachSan khachSan)
        {
            try
            {
                khachSan.Anh = "";
                var f = Request.Files["ImageFile"];
                if (f != null && f.ContentLength > 0)
                {
                    string FileName = System.IO.Path.GetFileName(f.FileName);
                    string UploadPath = Path.Combine(Server.MapPath("~/Image/Khách sạn/"), FileName);
                    f.SaveAs(UploadPath);
                    khachSan.Anh = FileName;
                }
                db.KhachSans.Add(khachSan);
                db.SaveChanges();
                return RedirectToAction("Index__Admin");
            }
            catch (Exception ex)
            {
                ViewBag.Error = "Lỗi nhập dữ liệu !" + ex.Message;
                ViewBag.IDThanhPho = new SelectList(db.ThanhPhoes, "IDThanhPho", "Ten", khachSan.IDThanhPho);
                return View(khachSan);
            }
        }

        // GET: KhachSans/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            KhachSan khachSan = db.KhachSans.Find(id);
            if (khachSan == null)
            {
                return HttpNotFound();
            }
            ViewBag.IDThanhPho = new SelectList(db.ThanhPhoes, "IDThanhPho", "Ten", khachSan.IDThanhPho);
            return View(khachSan);
        }

        // POST: KhachSans/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IDKS,Ten,DiaChi,Anh,MoTa,IDThanhPho")] KhachSan khachSan)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    khachSan.Anh = "";
                    var f = Request.Files["ImageFile"];
                    if (f != null && f.ContentLength > 0)
                    {
                        string FileName = System.IO.Path.GetFileName(f.FileName);
                        string UpLoadPath = Server.MapPath("~/Image/Khách Sạn/" + FileName);
                        f.SaveAs(UpLoadPath);
                        khachSan.Anh = FileName;
                    }
                    db.Entry(khachSan).State = EntityState.Modified;
                    db.SaveChanges();
                }
                return RedirectToAction("Index__Admin");
            }
            catch (Exception ex)
            {
                ViewBag.Error = "Lỗi nhập dữ liệu !" + ex.Message;
                ViewBag.IDThanhPho = new SelectList(db.ThanhPhoes, "IDThanhPho", "Ten", khachSan.IDThanhPho);
                return View(khachSan);
            }
        }

        // GET: KhachSans/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            KhachSan khachSan = db.KhachSans.Find(id);
            if (khachSan == null)
            {
                return HttpNotFound();
            }
            return View(khachSan);
        }

        // POST: KhachSans/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            KhachSan khachSan = db.KhachSans.Find(id);
            try
            {
                db.KhachSans.Remove(khachSan);
                db.SaveChanges();
                return RedirectToAction("Index__Admin");
            }
            catch (Exception ex)
            {
                ViewBag.Error = "Không được xóa bản ghi này !" + ex.Message;
                return View("Delete", khachSan);
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

Nhom14_ChuDu/Controllers/ThanhPhoesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Nhom14_ChuDu.Models;
using PagedList;

namespace Nhom14_ChuDu.Controllers
{
    public class ThanhPhoesController : Controller
    {
        private ChuDu24 db = new ChuDu24();

        // GET: ThanhPhoes
        public ActionResult Index(string sortOrder, string searchString, string currentFilter, int? page)
        {
            //các biến sắp xếp
            ViewBag.CurrentSort = sortOrder;

            ViewBag.SapTheoTen = String.IsNullOrEmpty(sortOrder) ? "ten_desc" : "";

            //lấy giá trị của bộ lọc dữ liệu hiện tại
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter = searchString;

            var thanhPho = db.ThanhPhoes.Select(tp => tp);

            //lọc theo tên hàng
            if (!String.IsNullOrEmpty(searchString))
            {
                thanhPho = thanhPho.Where(k => k.Ten.Contains(searchString));
            }
            switch (sortOrder)
            {
                case "ten_desc":
                    thanhPho = thanhPho.OrderByDescending(k => k.Ten);
                    break;
                default:
                    thanhPho = thanhPho.OrderBy(k => k.Ten);
                    break;
            }

            //thanhPho = thanhPho.OrderBy(tp => tp.IDThanhPho);
            int pageSize = 5;
            int pageNumber = (page ?? 1);

            return View(thanhPho.ToPagedList(pageNumber, pageSize));
        }

        // GET: ThanhPhoes/Details/5
        public PartialViewResult _DsThanhPho()
        {
            var thanhPhoes = db.ThanhPhoes.Select(p => p);
            return PartialView(thanhPhoes);
        }
        // GET: ThanhPhoes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ThanhPho thanhPho = db.ThanhPhoes.Find(id);
            if (thanhPho == null)
            {
                return HttpNotFound();
            }
            return View(thanhPho);
        }

        // GET: ThanhPhoes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ThanhPhoes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IDThanhPho,Ten,Anh")] ThanhPho thanhPho)
        {
            try
            {
                thanhPho.Anh = "";
                var f = Request.Files["ImageFile"];
                if (f != null && f.ContentLength > 0)
                {
                    string FileName = System.IO.Path.GetFileName(f.FileName);
                    string UploadPath = Path.Combine(Server.MapPath("~/Image/Tỉnh thành/"), FileName);
                    f.SaveAs(UploadPath);
                    thanhPho.Anh = FileName;
                }
                db.ThanhPhoes.Add(thanhPho);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch(Exception ex)
            {
                ViewBag.Error = "Lỗi nhập dữ liệu !" + ex.Message;
                return View(thanhPho);
            }
        }

        // GET: ThanhPhoes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ThanhPho thanhPho = db.ThanhPhoes.Find(id);
            if (thanhPho == null)
            {
                return HttpNotFound();
            }
            return View(thanhPho);
        }

        // POST: ThanhPhoes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IDThanhPho,Ten,Anh")] ThanhPho thanhPho)
        {
            try
            {
                thanhPho.Anh = "";
                var f = Request.Files["ImageFile"];
                if (f != null && f.ContentLength > 0)
                {
                    string FileName = System.IO.Path.GetFileName(f.FileName);
                    string UploadPath = Path.Combine(Server.MapPath("~/Image/Tỉnh thành/") + FileName);
                    f.SaveAs(UploadPath);
                    thanhPho.Anh = FileName;
                }
                db.Entry(thanhPho).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch(Exception ex)
            {
                ViewBag.Error = "Lỗi nhập dữ liệu !" + ex.Message;
                return View(thanhPho);
            }
        }

        // GET: ThanhPhoes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ThanhPho thanhPho = db.ThanhPhoes.Find(id);
            if (thanhPho == null)
            {
                return HttpNotFound();
            }
            return View(thanhPho);
        }

        // POST: ThanhPhoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ThanhPho thanhPho = db.ThanhPhoes.Find(id);
            try
            {
                db.ThanhPhoes.Remove(thanhPho);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ViewBag.Error = "Không được xóa bản ghi này !" + ex.Message;
                return View("Delete", thanhPho);
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public PartialViewResult _SearchThanhPho()
        {
            var thanhPhoes = db.ThanhPhoes.Select(p => p);
            return PartialView(thanhPhoes);
        }
    }
}

Nhom14_ChuDu/Views/Home/DangNhap.cshtml
@model Nhom14_ChuDu.Models.TaiKhoan

@{
    ViewBag.Title = "Đăng nhập";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Đăng nhập</title>
    <link rel="stylesheet" href="~/Content/login.css" />
</head><!--/head-->

<body>
    <!--header bố cục trang -->
    <div class="login-wrap" style="margin-top: 30px">
        <div class="login-html" style="background-color: #86b817;">
            <input id="tab-1" type="radio" name="tab" class="sign-in" checked><label style="font-weight: bolder" for="tab-1" class="tab">ĐĂNG NHẬP</label>
            <div class="login-form">
                <div>
                    @using (Html.BeginForm("DangNhap", "Home", FormMethod.Post))
                    {
                    @Html.AntiForgeryToken()
                        <div class="group">
                            @Html.TextBoxFor(m => m.Ten, "", new { @class = "form-control", @placeholder = "Tên Đăng Nhập" })
                        </div>
                        <div class="group">
                            @Html.TextBoxFor(m => m.MatKhau, "", new { @class = "form-control", @Type = "password", @placeholder = "Mật Khẩu" })
                        </div>
                        <div class="group">
                            <input id="check" type="checkbox" class="check" checked>
                            <label for="check"><span class="icon"></span> Giữ đăng nhập lần sau</label>
                        </div>
                        <div class="group">
                            <input style="background-color: aliceblue; color: black; font-weight: bolder" type="submit" class="button" value="Đăng nhập">
                        </div>
                        <div style="color: red">
                            @ViewBag.error
                        </div>
                    }
                    <div class="hr"></div>
                    <div class="foot-lnk">
                        <a href="#forgot">Quên mật khẩu?</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

   


    <!--header bố cục trang -->

  
</body>
</html>

Nhom14_ChuDu/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Trang chủ";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@{
    Html.RenderAction("_SearchThanhPho", "ThanhPhoes");
}
@Html.Partial("Slider")
@Html.Partial("SliderBot")
@{
    Html.RenderAction("_DsKhachSan", "KhachSans");
}
@{

    Html.RenderAction("_DsThanhPho", "ThanhPhoes");
}

Nhom14_ChuDu/Views/Home/Index_admin.cshtml
@{ ViewBag.Title = "Index_admin";
    Layout = "~/Views/Shared/_Admin.cshtml"; }

@model PagedList.IPagedList<Nhom14_ChuDu.Models.KhachSan>
@{
    Html.RenderAction("Index__detail", "KhachSans");
}

Nhom14_ChuDu/Views/Home/register.cshtml
@model Nhom14_ChuDu.Models.TaiKhoan

@{
    ViewBag.Title = "Đăng ký";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Đăng nhập | Đăng kí</title>
    <link rel="stylesheet" href="~/Content/login.css" />
</head><!--/head-->

<body>
    <!--header bố cục trang -->
    <div class="login-wrap" style="margin-top: 30px; margin-bottom: 400px">
        <div class="login-html" style="background-color: #86b817; height: 100%">
            <input id="tab-2" type="radio" name="tab" class="sign-up"><label style="font-weight: bolder" for="tab-2" class="tab">ĐĂNG KÝ</label>
            <div class="login-form">
                <div>
                    @using (Html.BeginForm("register", "Home", FormMethod.Post, new { enctype = "multipart/form-data", @class = "draw_form", @id = "draw_form" }))
                    {
                        @Html.AntiForgeryToken()
                        <div class="group">
                            <input class="form-control" placeholder="Tên" type="text" id="thiet_ke_san_pham" name="Ten" />
                        </div>
                        <div class="group">
                            <input class="form-control" placeholder="Mật khẩu" type="password" id="thiet_ke_san_pham" name="MatKhau" />
                        </div>
                        <div class="group">
                            <input class="form-control" placeholder="Nhập lại Mật khẩu" type="password" id="thiet_ke_san_pham" name="retrypassword" />
                        </div>
                        <div class="group">
                            <input class="form-control" placeholder="Địa chỉ" type="text" id="thiet_ke_san_pham" name="DiaChi" />
                        </div>
                        <div class="group">
                            <input class="form-control" placeholder="Số điện thoại" type="text" id="thiet_ke_san_pham" name="SDT" />
                        </div>
                        <div class="group">
                            <p> @ViewBag.errorPass</p>
                        </div>
                        <div class="group">
                            <input style="background-color: aliceblue; color: black; font-weight: bolder" type="submit" class="button" value="Đăng ký">
                        </div>
                        <div class="hr"></div>
                    }
                </div>
            </div>
        </div>
    </div>




    <!--header bố cục trang -->


</body>
</html>